name:                graphie
version:             0.1.0.0
github:              "acrylic-origami/graphie"
license:             BSD3
author:              "Derek Lam"
maintainer:          "derek@lam.io"
copyright:           "2020 Derek Lam"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/acrylic-origami/graphie#readme>

dependencies:
- base >= 4.7 && < 5
- array
- aeson
- ghc
- ghc-prof
- ghc-paths
- mtl
- directory
- filepath
- text
- containers
- lens
- hasbolt
- hasbolt-extras
- data-default
- bytestring
- utf8-string
- cassava
- transformers

library:
  source-dirs: src

executables:
  graphie-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphie

tests:
  graphie-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - graphie
